### PR TITLE
Implemented ROT13 functionality in YourTextSite Project

### PR DESCRIPTION
**Pull request by sumitkumarju**
# Related Issue
- Implemented ROT13 functionality in YourTextSite Project
 Fixed Issue #191

# Proposed Changes
- Added a button for ROT13 functionality.
- ROT13 function is implemented as getting the ASCII code of the letter (let say x )(excluding space) and replacing it with the 
letter whose ASCII is (x+13) in a circular manner 

# Additional Info

# Checklist
- [x] Tests
- [ ] Translations
- [ ] Documentation
- [x] Starred the repo

# Screenshots
 
Origianl        | Updated
:----------------:|:----------------:
 image  | **image**

### CODE REVIEW

**Comment by mayankjain25** [comment]
Screenshots?

**Comment by sumitkumarju** [comment]
image
@mayankjain25

**Comment by nishant-giri** [comment]
@sumitkumarju, kindly edit your initial comment and add the necessary details like proposed changes, screenshots of both original and updated. Please do the needful first.

**Comment by sumitkumarju** [comment]
@nishant-giri  @mayankjain25  Done. Kindly Check

**Comment by mayankjain25** [comment]
@sumitkumarju looks good to me

**Pull request merged**
