### PR TITLE
added dijkstra algo in python

### PR DESCRIPTION
**Pull request by ayush523**
Fixed issue #105

### CODE REVIEW

**Review by nishant-giri — CHANGES_REQUESTED** [review]
@ayush523, can you kindly put comments in your code?

**Comment by ayush523** [comment]
Hi @nishant-giri ,should i do it here or create a separate pull request?

**Comment by nishant-giri** [comment]
@ayush523, it's fine now. No need for the changes.

**Comment by ayush523** [comment]
okay

**Pull request merged**
