### PR TITLE
Change background in calculator

### PR DESCRIPTION
**Pull request by HVbajoria**
I have tried solving the issue number #232 .

Changes I have made :
- Added a new gradient blue background that makes the application look more unique.
- Added a typewriter animation to the heading.

I have tried my best to resolve the issue please check it out and let me know if any changes are required. 
Thank you.

### CODE REVIEW

**Comment by nishant-giri** [comment]
@HVbajoria, kindly resolve the conflicts.

**Comment by HVbajoria** [comment]
Okay just a minute @nishant-giri

**Comment by HVbajoria** [comment]
I have resolved the merge conflicts can you please check now @nishant-giri . 
Thank you.

**Comment by HVbajoria** [comment]
Sir could you please tell me if is this issue still open ? 
If yes can you please checkout my work I have added 2 new features to it.

**Review by nishant-giri — COMMENTED** [review]
The issue is closed now.

**Pull request closed without merging**
