### PR TITLE
improved messege

### PR DESCRIPTION
**Pull request by bipinparajuli**
# Related Issue
- Mention the issue number that you have solved
For ex: Fixed Issue #102

# Proposed Changes
- Change 1
- Change 2

# Additional Info
- Any additional information or context

# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentation
- [ ] Starred the repo

# Screenshots
 
Origianl        | Updated
:----------------:|:----------------:
** original screenshots ** | ** updated screenshot **

### CODE REVIEW

**Comment by SaniyaBhargav** [comment]
@bipinparajuli Firstly, you have mentioned the wrong issue number. Kindly correct it.
Secondly, kindly make the required edits in the documentation as well.

**Review by nishant-giri — CHANGES_REQUESTED** [review]
@bipinparajuli, kindly mention correct issue in your comment and also make edits in the documentation of the project.

**Comment by bipinparajuli** [comment]
can you please let me know where should I mention issue?

**Comment by nishant-giri** [comment]
@bipinparajuli, in the comment. When you're making a PR, kindly mention the issue which you've resolved. And delete those lines from comment which are not required.

**Comment by arnab8335** [comment]
Also @bipinparajuli add the screenshots of previous and the updated one. It will be easier for us to track and merge your request and do the needful as commented.

**Comment by bipinparajuli** [comment]
Improved #196

**Comment by SaniyaBhargav** [comment]
The place where you have written Fixed issue #102 in description just replace the issue number with the issue number of this one

**Comment by nishant-giri** [comment]
@bipinparajuli, make the edits in your initial comment.

**Review by nishant-giri — COMMENTED** [review]
@bipinparajuli, closing this PR for now. Kindly make the required changes and create a new PR, if you want.

**Pull request closed without merging**
